### ISSUE TITLE
[enhancement] Adding the ability to recover the blinding factor from an encrypted message

### ISSUE THREAD

**Issue by kran6a** [juanelas/paillier-js#1]
For my use case I need to recover the blinding factor (r) used when a number was encrypted having the ciphertext and the private key.
I have tried looking for a library implementing it in other languages but there was none so I tried to implement [this](https://crypto.stackexchange.com/questions/64343/how-to-calculate-random-factor-in-paillier-cryptosystem) myself but I was not able to get it to work.

**Comment by juanelas** [comment]
It's been a long time since you open this issue, @kran6a, but I have implemented it in [paillier-bigint](https://github.com/juanelas/paillier-bigint) if you want to take a look. Hope it could be still useful.
